del "*.suo" /Q/A
del "classify.web.demo\bin\*.pdb" /Q
del "classify.web.demo\*.csproj.user" /Q
rd "classify.web.demo\obj" /S/Q
rd "classify\bin" /S/Q
rd "classify\obj" /S/Q
rd "classify.model-builder.console\bin" /S/Q
rd "classify.model-builder.console\obj" /S/Q
rd "captcha\bin" /S/Q
rd "captcha\obj" /S/Q